//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `AuthModule.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __AuthModule_h__
#define __AuthModule_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace AuthModule
{

class AuthInterface;
class AuthInterfacePrx;

}

namespace AuthModule
{

enum class LoginResponse : unsigned char
{
    NotIdentified,
    Identified,
    LoggedIn,
    IncorectPassword,
    ThrottlingActivated
};

enum class RegistrationResponse : unsigned char
{
    RegistrationSuccessful,
    EmailAlreadyExists,
    PhoneAlreadyExists
};

enum class ChangePasswordResponse : unsigned char
{
    PasswordChanged,
    PasswordNotChanged,
    OldPasswordIncorrect,
    ThrottlingActivated
};

using ImageData = ::std::vector<::Ice::Byte>;

struct LoginInfo
{
    ::std::string email;
    ::std::string password;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::std::string&, const ::std::string&> ice_tuple() const
    {
        return std::tie(email, password);
    }
};

struct RegistrationInfo
{
    ::std::string name;
    ::AuthModule::ImageData photo;
    ::std::string email;
    ::std::string phone;
    ::std::string password;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::std::string&, const ::AuthModule::ImageData&, const ::std::string&, const ::std::string&, const ::std::string&> ice_tuple() const
    {
        return std::tie(name, photo, email, phone, password);
    }
};

struct LoginReturn
{
    ::AuthModule::ImageData photo;
    ::std::string name;
    ::std::string email;
    ::std::string token;
    ::AuthModule::LoginResponse loginResponse;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::AuthModule::ImageData&, const ::std::string&, const ::std::string&, const ::std::string&, const ::AuthModule::LoginResponse&> ice_tuple() const
    {
        return std::tie(photo, name, email, token, loginResponse);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace AuthModule
{

class AuthInterface : public virtual ::Ice::Object
{
public:

    using ProxyType = AuthInterfacePrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual LoginReturn loginUser(LoginInfo loginInfo, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_loginUser(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual RegistrationResponse registerUser(RegistrationInfo registrationInfo, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_registerUser(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual ChangePasswordResponse changePassword(::std::string userToken, ::std::string oldPassword, ::std::string newPassword, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_changePassword(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual ::std::string getUserName(::std::string userToken, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getUserName(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace AuthModule
{

class AuthInterfacePrx : public virtual ::Ice::Proxy<AuthInterfacePrx, ::Ice::ObjectPrx>
{
public:

    LoginReturn loginUser(const LoginInfo& loginInfo, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::AuthModule::LoginReturn>(true, this, &AuthInterfacePrx::_iceI_loginUser, loginInfo, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto loginUserAsync(const LoginInfo& loginInfo, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::AuthModule::LoginReturn>>().get_future())
    {
        return _makePromiseOutgoing<::AuthModule::LoginReturn, P>(false, this, &AuthInterfacePrx::_iceI_loginUser, loginInfo, context);
    }

    ::std::function<void()>
    loginUserAsync(const LoginInfo& loginInfo,
                   ::std::function<void(::AuthModule::LoginReturn)> response,
                   ::std::function<void(::std::exception_ptr)> ex = nullptr,
                   ::std::function<void(bool)> sent = nullptr,
                   const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::AuthModule::LoginReturn>(std::move(response), std::move(ex), std::move(sent), this, &AuthModule::AuthInterfacePrx::_iceI_loginUser, loginInfo, context);
    }

    /// \cond INTERNAL
    void _iceI_loginUser(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::AuthModule::LoginReturn>>&, const LoginInfo&, const ::Ice::Context&);
    /// \endcond

    RegistrationResponse registerUser(const RegistrationInfo& registrationInfo, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::AuthModule::RegistrationResponse>(true, this, &AuthInterfacePrx::_iceI_registerUser, registrationInfo, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto registerUserAsync(const RegistrationInfo& registrationInfo, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::AuthModule::RegistrationResponse>>().get_future())
    {
        return _makePromiseOutgoing<::AuthModule::RegistrationResponse, P>(false, this, &AuthInterfacePrx::_iceI_registerUser, registrationInfo, context);
    }

    ::std::function<void()>
    registerUserAsync(const RegistrationInfo& registrationInfo,
                      ::std::function<void(::AuthModule::RegistrationResponse)> response,
                      ::std::function<void(::std::exception_ptr)> ex = nullptr,
                      ::std::function<void(bool)> sent = nullptr,
                      const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::AuthModule::RegistrationResponse>(std::move(response), std::move(ex), std::move(sent), this, &AuthModule::AuthInterfacePrx::_iceI_registerUser, registrationInfo, context);
    }

    /// \cond INTERNAL
    void _iceI_registerUser(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::AuthModule::RegistrationResponse>>&, const RegistrationInfo&, const ::Ice::Context&);
    /// \endcond

    ChangePasswordResponse changePassword(const ::std::string& userToken, const ::std::string& oldPassword, const ::std::string& newPassword, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::AuthModule::ChangePasswordResponse>(true, this, &AuthInterfacePrx::_iceI_changePassword, userToken, oldPassword, newPassword, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto changePasswordAsync(const ::std::string& userToken, const ::std::string& oldPassword, const ::std::string& newPassword, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::AuthModule::ChangePasswordResponse>>().get_future())
    {
        return _makePromiseOutgoing<::AuthModule::ChangePasswordResponse, P>(false, this, &AuthInterfacePrx::_iceI_changePassword, userToken, oldPassword, newPassword, context);
    }

    ::std::function<void()>
    changePasswordAsync(const ::std::string& userToken, const ::std::string& oldPassword, const ::std::string& newPassword,
                        ::std::function<void(::AuthModule::ChangePasswordResponse)> response,
                        ::std::function<void(::std::exception_ptr)> ex = nullptr,
                        ::std::function<void(bool)> sent = nullptr,
                        const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::AuthModule::ChangePasswordResponse>(std::move(response), std::move(ex), std::move(sent), this, &AuthModule::AuthInterfacePrx::_iceI_changePassword, userToken, oldPassword, newPassword, context);
    }

    /// \cond INTERNAL
    void _iceI_changePassword(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::AuthModule::ChangePasswordResponse>>&, const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context&);
    /// \endcond

    ::std::string getUserName(const ::std::string& userToken, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::std::string>(true, this, &AuthInterfacePrx::_iceI_getUserName, userToken, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getUserNameAsync(const ::std::string& userToken, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::std::string>>().get_future())
    {
        return _makePromiseOutgoing<::std::string, P>(false, this, &AuthInterfacePrx::_iceI_getUserName, userToken, context);
    }

    ::std::function<void()>
    getUserNameAsync(const ::std::string& userToken,
                     ::std::function<void(::std::string)> response,
                     ::std::function<void(::std::exception_ptr)> ex = nullptr,
                     ::std::function<void(bool)> sent = nullptr,
                     const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::std::string>(std::move(response), std::move(ex), std::move(sent), this, &AuthModule::AuthInterfacePrx::_iceI_getUserName, userToken, context);
    }

    /// \cond INTERNAL
    void _iceI_getUserName(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::string>>&, const ::std::string&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    AuthInterfacePrx() = default;
    friend ::std::shared_ptr<AuthInterfacePrx> IceInternal::createProxy<AuthInterfacePrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::AuthModule::LoginResponse>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 4;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<>
struct StreamableTraits< ::AuthModule::RegistrationResponse>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 2;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<>
struct StreamableTraits< ::AuthModule::ChangePasswordResponse>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 3;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<>
struct StreamableTraits<::AuthModule::LoginInfo>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 2;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::AuthModule::LoginInfo, S>
{
    static void read(S* istr, ::AuthModule::LoginInfo& v)
    {
        istr->readAll(v.email, v.password);
    }
};

template<>
struct StreamableTraits<::AuthModule::RegistrationInfo>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 5;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::AuthModule::RegistrationInfo, S>
{
    static void read(S* istr, ::AuthModule::RegistrationInfo& v)
    {
        istr->readAll(v.name, v.photo, v.email, v.phone, v.password);
    }
};

template<>
struct StreamableTraits<::AuthModule::LoginReturn>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 5;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::AuthModule::LoginReturn, S>
{
    static void read(S* istr, ::AuthModule::LoginReturn& v)
    {
        istr->readAll(v.photo, v.name, v.email, v.token, v.loginResponse);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace AuthModule
{

using AuthInterfacePtr = ::std::shared_ptr<AuthInterface>;
using AuthInterfacePrxPtr = ::std::shared_ptr<AuthInterfacePrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace AuthModule
{

class AuthInterface;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< AuthInterface>&);
::IceProxy::Ice::Object* upCast(AuthInterface*);
/// \endcond

}

}

namespace AuthModule
{

class AuthInterface;
/// \cond INTERNAL
::Ice::Object* upCast(AuthInterface*);
/// \endcond
typedef ::IceInternal::Handle< AuthInterface> AuthInterfacePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::AuthModule::AuthInterface> AuthInterfacePrx;
typedef AuthInterfacePrx AuthInterfacePrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(AuthInterfacePtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace AuthModule
{

enum LoginResponse
{
    NotIdentified,
    Identified,
    LoggedIn,
    IncorectPassword,
    ThrottlingActivated
};

enum RegistrationResponse
{
    RegistrationSuccessful,
    EmailAlreadyExists,
    PhoneAlreadyExists
};

enum ChangePasswordResponse
{
    PasswordChanged,
    PasswordNotChanged,
    OldPasswordIncorrect,
    ThrottlingActivated
};

typedef ::std::vector< ::Ice::Byte> ImageData;

struct LoginInfo
{
    ::std::string email;
    ::std::string password;

    bool operator==(const LoginInfo& rhs_) const
    {
        if(this == &rhs_)
        {
            return true;
        }
        if(email != rhs_.email)
        {
            return false;
        }
        if(password != rhs_.password)
        {
            return false;
        }
        return true;
    }

    bool operator<(const LoginInfo& rhs_) const
    {
        if(this == &rhs_)
        {
            return false;
        }
        if(email < rhs_.email)
        {
            return true;
        }
        else if(rhs_.email < email)
        {
            return false;
        }
        if(password < rhs_.password)
        {
            return true;
        }
        else if(rhs_.password < password)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const LoginInfo& rhs_) const
    {
        return !operator==(rhs_);
    }
    bool operator<=(const LoginInfo& rhs_) const
    {
        return operator<(rhs_) || operator==(rhs_);
    }
    bool operator>(const LoginInfo& rhs_) const
    {
        return !operator<(rhs_) && !operator==(rhs_);
    }
    bool operator>=(const LoginInfo& rhs_) const
    {
        return !operator<(rhs_);
    }
};

struct RegistrationInfo
{
    ::std::string name;
    ::AuthModule::ImageData photo;
    ::std::string email;
    ::std::string phone;
    ::std::string password;
};

struct LoginReturn
{
    ::AuthModule::ImageData photo;
    ::std::string name;
    ::std::string email;
    ::std::string token;
    ::AuthModule::LoginResponse loginResponse;
};

}

namespace AuthModule
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::AuthModule::AuthInterface::begin_loginUser.
 * Create a wrapper instance by calling ::AuthModule::newCallback_AuthInterface_loginUser.
 */
class Callback_AuthInterface_loginUser_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AuthInterface_loginUser_Base> Callback_AuthInterface_loginUserPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::AuthModule::AuthInterface::begin_registerUser.
 * Create a wrapper instance by calling ::AuthModule::newCallback_AuthInterface_registerUser.
 */
class Callback_AuthInterface_registerUser_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AuthInterface_registerUser_Base> Callback_AuthInterface_registerUserPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::AuthModule::AuthInterface::begin_changePassword.
 * Create a wrapper instance by calling ::AuthModule::newCallback_AuthInterface_changePassword.
 */
class Callback_AuthInterface_changePassword_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AuthInterface_changePassword_Base> Callback_AuthInterface_changePasswordPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::AuthModule::AuthInterface::begin_getUserName.
 * Create a wrapper instance by calling ::AuthModule::newCallback_AuthInterface_getUserName.
 */
class Callback_AuthInterface_getUserName_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AuthInterface_getUserName_Base> Callback_AuthInterface_getUserNamePtr;

}

namespace IceProxy
{

namespace AuthModule
{

class AuthInterface : public virtual ::Ice::Proxy<AuthInterface, ::IceProxy::Ice::Object>
{
public:

    ::AuthModule::LoginReturn loginUser(const ::AuthModule::LoginInfo& loginInfo, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_loginUser(_iceI_begin_loginUser(loginInfo, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_loginUser(const ::AuthModule::LoginInfo& loginInfo, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_loginUser(loginInfo, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_loginUser(const ::AuthModule::LoginInfo& loginInfo, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_loginUser(loginInfo, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_loginUser(const ::AuthModule::LoginInfo& loginInfo, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_loginUser(loginInfo, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_loginUser(const ::AuthModule::LoginInfo& loginInfo, const ::AuthModule::Callback_AuthInterface_loginUserPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_loginUser(loginInfo, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_loginUser(const ::AuthModule::LoginInfo& loginInfo, const ::Ice::Context& context, const ::AuthModule::Callback_AuthInterface_loginUserPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_loginUser(loginInfo, context, cb, cookie);
    }

    ::AuthModule::LoginReturn end_loginUser(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_loginUser(const ::AuthModule::LoginInfo&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::AuthModule::RegistrationResponse registerUser(const ::AuthModule::RegistrationInfo& registrationInfo, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_registerUser(_iceI_begin_registerUser(registrationInfo, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_registerUser(const ::AuthModule::RegistrationInfo& registrationInfo, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_registerUser(registrationInfo, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_registerUser(const ::AuthModule::RegistrationInfo& registrationInfo, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_registerUser(registrationInfo, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_registerUser(const ::AuthModule::RegistrationInfo& registrationInfo, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_registerUser(registrationInfo, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_registerUser(const ::AuthModule::RegistrationInfo& registrationInfo, const ::AuthModule::Callback_AuthInterface_registerUserPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_registerUser(registrationInfo, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_registerUser(const ::AuthModule::RegistrationInfo& registrationInfo, const ::Ice::Context& context, const ::AuthModule::Callback_AuthInterface_registerUserPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_registerUser(registrationInfo, context, cb, cookie);
    }

    ::AuthModule::RegistrationResponse end_registerUser(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_registerUser(const ::AuthModule::RegistrationInfo&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::AuthModule::ChangePasswordResponse changePassword(const ::std::string& userToken, const ::std::string& oldPassword, const ::std::string& newPassword, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_changePassword(_iceI_begin_changePassword(userToken, oldPassword, newPassword, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_changePassword(const ::std::string& userToken, const ::std::string& oldPassword, const ::std::string& newPassword, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_changePassword(userToken, oldPassword, newPassword, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_changePassword(const ::std::string& userToken, const ::std::string& oldPassword, const ::std::string& newPassword, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_changePassword(userToken, oldPassword, newPassword, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_changePassword(const ::std::string& userToken, const ::std::string& oldPassword, const ::std::string& newPassword, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_changePassword(userToken, oldPassword, newPassword, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_changePassword(const ::std::string& userToken, const ::std::string& oldPassword, const ::std::string& newPassword, const ::AuthModule::Callback_AuthInterface_changePasswordPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_changePassword(userToken, oldPassword, newPassword, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_changePassword(const ::std::string& userToken, const ::std::string& oldPassword, const ::std::string& newPassword, const ::Ice::Context& context, const ::AuthModule::Callback_AuthInterface_changePasswordPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_changePassword(userToken, oldPassword, newPassword, context, cb, cookie);
    }

    ::AuthModule::ChangePasswordResponse end_changePassword(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_changePassword(const ::std::string&, const ::std::string&, const ::std::string&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::std::string getUserName(const ::std::string& userToken, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getUserName(_iceI_begin_getUserName(userToken, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getUserName(const ::std::string& userToken, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getUserName(userToken, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getUserName(const ::std::string& userToken, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getUserName(userToken, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getUserName(const ::std::string& userToken, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getUserName(userToken, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getUserName(const ::std::string& userToken, const ::AuthModule::Callback_AuthInterface_getUserNamePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getUserName(userToken, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getUserName(const ::std::string& userToken, const ::Ice::Context& context, const ::AuthModule::Callback_AuthInterface_getUserNamePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getUserName(userToken, context, cb, cookie);
    }

    ::std::string end_getUserName(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getUserName(const ::std::string&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace AuthModule
{

class AuthInterface : public virtual ::Ice::Object
{
public:

    typedef AuthInterfacePrx ProxyType;
    typedef AuthInterfacePtr PointerType;

    virtual ~AuthInterface();

#ifdef ICE_CPP11_COMPILER
    AuthInterface() = default;
    AuthInterface(const AuthInterface&) = default;
    AuthInterface& operator=(const AuthInterface&) = default;
#endif

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual LoginReturn loginUser(const LoginInfo& loginInfo, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_loginUser(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual RegistrationResponse registerUser(const RegistrationInfo& registrationInfo, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_registerUser(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual ChangePasswordResponse changePassword(const ::std::string& userToken, const ::std::string& oldPassword, const ::std::string& newPassword, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_changePassword(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual ::std::string getUserName(const ::std::string& userToken, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getUserName(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const AuthInterface& lhs, const AuthInterface& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const AuthInterface& lhs, const AuthInterface& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::AuthModule::LoginResponse>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 4;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<>
struct StreamableTraits< ::AuthModule::RegistrationResponse>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 2;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<>
struct StreamableTraits< ::AuthModule::ChangePasswordResponse>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 3;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

template<>
struct StreamableTraits< ::AuthModule::LoginInfo>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 2;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::AuthModule::LoginInfo, S>
{
    static void write(S* ostr, const ::AuthModule::LoginInfo& v)
    {
        ostr->write(v.email);
        ostr->write(v.password);
    }
};

template<typename S>
struct StreamReader< ::AuthModule::LoginInfo, S>
{
    static void read(S* istr, ::AuthModule::LoginInfo& v)
    {
        istr->read(v.email);
        istr->read(v.password);
    }
};

template<>
struct StreamableTraits< ::AuthModule::RegistrationInfo>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 5;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::AuthModule::RegistrationInfo, S>
{
    static void write(S* ostr, const ::AuthModule::RegistrationInfo& v)
    {
        ostr->write(v.name);
        ostr->write(v.photo);
        ostr->write(v.email);
        ostr->write(v.phone);
        ostr->write(v.password);
    }
};

template<typename S>
struct StreamReader< ::AuthModule::RegistrationInfo, S>
{
    static void read(S* istr, ::AuthModule::RegistrationInfo& v)
    {
        istr->read(v.name);
        istr->read(v.photo);
        istr->read(v.email);
        istr->read(v.phone);
        istr->read(v.password);
    }
};

template<>
struct StreamableTraits< ::AuthModule::LoginReturn>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 5;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::AuthModule::LoginReturn, S>
{
    static void write(S* ostr, const ::AuthModule::LoginReturn& v)
    {
        ostr->write(v.photo);
        ostr->write(v.name);
        ostr->write(v.email);
        ostr->write(v.token);
        ostr->write(v.loginResponse);
    }
};

template<typename S>
struct StreamReader< ::AuthModule::LoginReturn, S>
{
    static void read(S* istr, ::AuthModule::LoginReturn& v)
    {
        istr->read(v.photo);
        istr->read(v.name);
        istr->read(v.email);
        istr->read(v.token);
        istr->read(v.loginResponse);
    }
};

}
/// \endcond

namespace AuthModule
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::AuthModule::AuthInterface::begin_loginUser.
 * Create a wrapper instance by calling ::AuthModule::newCallback_AuthInterface_loginUser.
 */
template<class T>
class CallbackNC_AuthInterface_loginUser : public Callback_AuthInterface_loginUser_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const LoginReturn&);

    CallbackNC_AuthInterface_loginUser(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        AuthInterfacePrx proxy = AuthInterfacePrx::uncheckedCast(result->getProxy());
        LoginReturn ret;
        try
        {
            ret = proxy->end_loginUser(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_loginUser.
 */
template<class T> Callback_AuthInterface_loginUserPtr
newCallback_AuthInterface_loginUser(const IceUtil::Handle<T>& instance, void (T::*cb)(const LoginReturn&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AuthInterface_loginUser<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_loginUser.
 */
template<class T> Callback_AuthInterface_loginUserPtr
newCallback_AuthInterface_loginUser(T* instance, void (T::*cb)(const LoginReturn&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AuthInterface_loginUser<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::AuthModule::AuthInterface::begin_loginUser.
 * Create a wrapper instance by calling ::AuthModule::newCallback_AuthInterface_loginUser.
 */
template<class T, typename CT>
class Callback_AuthInterface_loginUser : public Callback_AuthInterface_loginUser_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const LoginReturn&, const CT&);

    Callback_AuthInterface_loginUser(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        AuthInterfacePrx proxy = AuthInterfacePrx::uncheckedCast(result->getProxy());
        LoginReturn ret;
        try
        {
            ret = proxy->end_loginUser(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_loginUser.
 */
template<class T, typename CT> Callback_AuthInterface_loginUserPtr
newCallback_AuthInterface_loginUser(const IceUtil::Handle<T>& instance, void (T::*cb)(const LoginReturn&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AuthInterface_loginUser<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_loginUser.
 */
template<class T, typename CT> Callback_AuthInterface_loginUserPtr
newCallback_AuthInterface_loginUser(T* instance, void (T::*cb)(const LoginReturn&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AuthInterface_loginUser<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::AuthModule::AuthInterface::begin_registerUser.
 * Create a wrapper instance by calling ::AuthModule::newCallback_AuthInterface_registerUser.
 */
template<class T>
class CallbackNC_AuthInterface_registerUser : public Callback_AuthInterface_registerUser_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(RegistrationResponse);

    CallbackNC_AuthInterface_registerUser(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        AuthInterfacePrx proxy = AuthInterfacePrx::uncheckedCast(result->getProxy());
        RegistrationResponse ret;
        try
        {
            ret = proxy->end_registerUser(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_registerUser.
 */
template<class T> Callback_AuthInterface_registerUserPtr
newCallback_AuthInterface_registerUser(const IceUtil::Handle<T>& instance, void (T::*cb)(RegistrationResponse), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AuthInterface_registerUser<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_registerUser.
 */
template<class T> Callback_AuthInterface_registerUserPtr
newCallback_AuthInterface_registerUser(T* instance, void (T::*cb)(RegistrationResponse), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AuthInterface_registerUser<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::AuthModule::AuthInterface::begin_registerUser.
 * Create a wrapper instance by calling ::AuthModule::newCallback_AuthInterface_registerUser.
 */
template<class T, typename CT>
class Callback_AuthInterface_registerUser : public Callback_AuthInterface_registerUser_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(RegistrationResponse, const CT&);

    Callback_AuthInterface_registerUser(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        AuthInterfacePrx proxy = AuthInterfacePrx::uncheckedCast(result->getProxy());
        RegistrationResponse ret;
        try
        {
            ret = proxy->end_registerUser(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_registerUser.
 */
template<class T, typename CT> Callback_AuthInterface_registerUserPtr
newCallback_AuthInterface_registerUser(const IceUtil::Handle<T>& instance, void (T::*cb)(RegistrationResponse, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AuthInterface_registerUser<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_registerUser.
 */
template<class T, typename CT> Callback_AuthInterface_registerUserPtr
newCallback_AuthInterface_registerUser(T* instance, void (T::*cb)(RegistrationResponse, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AuthInterface_registerUser<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::AuthModule::AuthInterface::begin_changePassword.
 * Create a wrapper instance by calling ::AuthModule::newCallback_AuthInterface_changePassword.
 */
template<class T>
class CallbackNC_AuthInterface_changePassword : public Callback_AuthInterface_changePassword_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(ChangePasswordResponse);

    CallbackNC_AuthInterface_changePassword(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        AuthInterfacePrx proxy = AuthInterfacePrx::uncheckedCast(result->getProxy());
        ChangePasswordResponse ret;
        try
        {
            ret = proxy->end_changePassword(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_changePassword.
 */
template<class T> Callback_AuthInterface_changePasswordPtr
newCallback_AuthInterface_changePassword(const IceUtil::Handle<T>& instance, void (T::*cb)(ChangePasswordResponse), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AuthInterface_changePassword<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_changePassword.
 */
template<class T> Callback_AuthInterface_changePasswordPtr
newCallback_AuthInterface_changePassword(T* instance, void (T::*cb)(ChangePasswordResponse), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AuthInterface_changePassword<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::AuthModule::AuthInterface::begin_changePassword.
 * Create a wrapper instance by calling ::AuthModule::newCallback_AuthInterface_changePassword.
 */
template<class T, typename CT>
class Callback_AuthInterface_changePassword : public Callback_AuthInterface_changePassword_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(ChangePasswordResponse, const CT&);

    Callback_AuthInterface_changePassword(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        AuthInterfacePrx proxy = AuthInterfacePrx::uncheckedCast(result->getProxy());
        ChangePasswordResponse ret;
        try
        {
            ret = proxy->end_changePassword(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_changePassword.
 */
template<class T, typename CT> Callback_AuthInterface_changePasswordPtr
newCallback_AuthInterface_changePassword(const IceUtil::Handle<T>& instance, void (T::*cb)(ChangePasswordResponse, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AuthInterface_changePassword<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_changePassword.
 */
template<class T, typename CT> Callback_AuthInterface_changePasswordPtr
newCallback_AuthInterface_changePassword(T* instance, void (T::*cb)(ChangePasswordResponse, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AuthInterface_changePassword<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::AuthModule::AuthInterface::begin_getUserName.
 * Create a wrapper instance by calling ::AuthModule::newCallback_AuthInterface_getUserName.
 */
template<class T>
class CallbackNC_AuthInterface_getUserName : public Callback_AuthInterface_getUserName_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_AuthInterface_getUserName(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        AuthInterfacePrx proxy = AuthInterfacePrx::uncheckedCast(result->getProxy());
        ::std::string ret;
        try
        {
            ret = proxy->end_getUserName(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_getUserName.
 */
template<class T> Callback_AuthInterface_getUserNamePtr
newCallback_AuthInterface_getUserName(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AuthInterface_getUserName<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_getUserName.
 */
template<class T> Callback_AuthInterface_getUserNamePtr
newCallback_AuthInterface_getUserName(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AuthInterface_getUserName<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::AuthModule::AuthInterface::begin_getUserName.
 * Create a wrapper instance by calling ::AuthModule::newCallback_AuthInterface_getUserName.
 */
template<class T, typename CT>
class Callback_AuthInterface_getUserName : public Callback_AuthInterface_getUserName_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_AuthInterface_getUserName(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        AuthInterfacePrx proxy = AuthInterfacePrx::uncheckedCast(result->getProxy());
        ::std::string ret;
        try
        {
            ret = proxy->end_getUserName(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_getUserName.
 */
template<class T, typename CT> Callback_AuthInterface_getUserNamePtr
newCallback_AuthInterface_getUserName(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AuthInterface_getUserName<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::AuthModule::AuthInterface::begin_getUserName.
 */
template<class T, typename CT> Callback_AuthInterface_getUserNamePtr
newCallback_AuthInterface_getUserName(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AuthInterface_getUserName<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
