//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `EventDataModule.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <EventDataModule.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_EventDataModule_EventsDataInterface_ids[2] =
{
    "::EventDataModule::EventsDataInterface",
    "::Ice::Object"
};
const ::std::string iceC_EventDataModule_EventsDataInterface_ops[] =
{
    "addServiceToEvent",
    "deleteRecord",
    "getClientsByName",
    "getClientsByPhone",
    "getEventData",
    "getEventsData",
    "getTenEvents",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "modifyClient",
    "modifyEventDoubleField",
    "modifyEventIntField",
    "modifyEventStringField",
    "modifyServiceDoubleField",
    "modifyServiceIntField",
    "modifyServiceStringField",
    "registerClient",
    "registerEvent"
};
const ::std::string iceC_EventDataModule_EventsDataInterface_getEventsData_name = "getEventsData";
const ::std::string iceC_EventDataModule_EventsDataInterface_getClientsByName_name = "getClientsByName";
const ::std::string iceC_EventDataModule_EventsDataInterface_getClientsByPhone_name = "getClientsByPhone";
const ::std::string iceC_EventDataModule_EventsDataInterface_getEventData_name = "getEventData";
const ::std::string iceC_EventDataModule_EventsDataInterface_getTenEvents_name = "getTenEvents";
const ::std::string iceC_EventDataModule_EventsDataInterface_registerEvent_name = "registerEvent";
const ::std::string iceC_EventDataModule_EventsDataInterface_modifyEventIntField_name = "modifyEventIntField";
const ::std::string iceC_EventDataModule_EventsDataInterface_modifyEventStringField_name = "modifyEventStringField";
const ::std::string iceC_EventDataModule_EventsDataInterface_modifyEventDoubleField_name = "modifyEventDoubleField";
const ::std::string iceC_EventDataModule_EventsDataInterface_addServiceToEvent_name = "addServiceToEvent";
const ::std::string iceC_EventDataModule_EventsDataInterface_modifyServiceIntField_name = "modifyServiceIntField";
const ::std::string iceC_EventDataModule_EventsDataInterface_modifyServiceStringField_name = "modifyServiceStringField";
const ::std::string iceC_EventDataModule_EventsDataInterface_modifyServiceDoubleField_name = "modifyServiceDoubleField";
const ::std::string iceC_EventDataModule_EventsDataInterface_registerClient_name = "registerClient";
const ::std::string iceC_EventDataModule_EventsDataInterface_modifyClient_name = "modifyClient";
const ::std::string iceC_EventDataModule_EventsDataInterface_deleteRecord_name = "deleteRecord";

}

bool
EventDataModule::EventsDataInterface::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_EventDataModule_EventsDataInterface_ids, iceC_EventDataModule_EventsDataInterface_ids + 2, s);
}

::std::vector<::std::string>
EventDataModule::EventsDataInterface::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_EventDataModule_EventsDataInterface_ids[0], &iceC_EventDataModule_EventsDataInterface_ids[2]);
}

::std::string
EventDataModule::EventsDataInterface::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
EventDataModule::EventsDataInterface::ice_staticId()
{
    static const ::std::string typeId = "::EventDataModule::EventsDataInterface";
    return typeId;
}

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_getEventsData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    istr->readAll(iceP_userToken);
    inS.endReadParams();
    SeqEventDataPack ret = this->getEventsData(::std::move(iceP_userToken), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_getClientsByName(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ::std::string iceP_partialName;
    istr->readAll(iceP_userToken, iceP_partialName);
    inS.endReadParams();
    SeqClients ret = this->getClientsByName(::std::move(iceP_userToken), ::std::move(iceP_partialName), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_getClientsByPhone(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ::std::string iceP_partialPhone;
    istr->readAll(iceP_userToken, iceP_partialPhone);
    inS.endReadParams();
    SeqClients ret = this->getClientsByPhone(::std::move(iceP_userToken), ::std::move(iceP_partialPhone), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_getEventData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    int iceP_eventId;
    istr->readAll(iceP_userToken, iceP_eventId);
    inS.endReadParams();
    EventDataPack ret = this->getEventData(::std::move(iceP_userToken), iceP_eventId, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_getTenEvents(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ::std::string iceP_fromDate;
    int iceP_offset;
    istr->readAll(iceP_userToken, iceP_fromDate, iceP_offset);
    inS.endReadParams();
    SeqEventDataPack ret = this->getTenEvents(::std::move(iceP_userToken), ::std::move(iceP_fromDate), iceP_offset, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_registerEvent(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    EventDataPack iceP_eventDataPack;
    istr->readAll(iceP_userToken, iceP_eventDataPack);
    inS.endReadParams();
    EventDataPack ret = this->registerEvent(::std::move(iceP_userToken), ::std::move(iceP_eventDataPack), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyEventIntField(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    int iceP_eventId;
    EventField iceP_field;
    int iceP_newValue;
    istr->readAll(iceP_userToken, iceP_eventId, iceP_field, iceP_newValue);
    inS.endReadParams();
    this->modifyEventIntField(::std::move(iceP_userToken), iceP_eventId, iceP_field, iceP_newValue, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyEventStringField(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    int iceP_eventId;
    EventField iceP_field;
    ::std::string iceP_newValue;
    istr->readAll(iceP_userToken, iceP_eventId, iceP_field, iceP_newValue);
    inS.endReadParams();
    this->modifyEventStringField(::std::move(iceP_userToken), iceP_eventId, iceP_field, ::std::move(iceP_newValue), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyEventDoubleField(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    int iceP_eventId;
    EventField iceP_field;
    double iceP_newValue;
    istr->readAll(iceP_userToken, iceP_eventId, iceP_field, iceP_newValue);
    inS.endReadParams();
    this->modifyEventDoubleField(::std::move(iceP_userToken), iceP_eventId, iceP_field, iceP_newValue, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_addServiceToEvent(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ServiceData iceP_serviceData;
    istr->readAll(iceP_userToken, iceP_serviceData);
    inS.endReadParams();
    this->addServiceToEvent(::std::move(iceP_userToken), ::std::move(iceP_serviceData), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyServiceIntField(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    int iceP_serviceId;
    ServiceField iceP_field;
    int iceP_newValue;
    istr->readAll(iceP_userToken, iceP_serviceId, iceP_field, iceP_newValue);
    inS.endReadParams();
    this->modifyServiceIntField(::std::move(iceP_userToken), iceP_serviceId, iceP_field, iceP_newValue, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyServiceStringField(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    int iceP_serviceId;
    ServiceField iceP_field;
    ::std::string iceP_newValue;
    istr->readAll(iceP_userToken, iceP_serviceId, iceP_field, iceP_newValue);
    inS.endReadParams();
    this->modifyServiceStringField(::std::move(iceP_userToken), iceP_serviceId, iceP_field, ::std::move(iceP_newValue), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyServiceDoubleField(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    int iceP_serviceId;
    ServiceField iceP_field;
    double iceP_newValue;
    istr->readAll(iceP_userToken, iceP_serviceId, iceP_field, iceP_newValue);
    inS.endReadParams();
    this->modifyServiceDoubleField(::std::move(iceP_userToken), iceP_serviceId, iceP_field, iceP_newValue, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_registerClient(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ClientData iceP_clientData;
    istr->readAll(iceP_userToken, iceP_clientData);
    inS.endReadParams();
    int ret = this->registerClient(::std::move(iceP_userToken), ::std::move(iceP_clientData), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyClient(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ClientData iceP_clientData;
    istr->readAll(iceP_userToken, iceP_clientData);
    inS.endReadParams();
    this->modifyClient(::std::move(iceP_userToken), ::std::move(iceP_clientData), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_deleteRecord(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_userToken;
    Table iceP_table;
    int iceP_id;
    istr->readAll(iceP_userToken, iceP_table, iceP_id);
    inS.endReadParams();
    this->deleteRecord(::std::move(iceP_userToken), iceP_table, iceP_id, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_EventDataModule_EventsDataInterface_ops, iceC_EventDataModule_EventsDataInterface_ops + 20, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_EventDataModule_EventsDataInterface_ops)
    {
        case 0:
        {
            return _iceD_addServiceToEvent(in, current);
        }
        case 1:
        {
            return _iceD_deleteRecord(in, current);
        }
        case 2:
        {
            return _iceD_getClientsByName(in, current);
        }
        case 3:
        {
            return _iceD_getClientsByPhone(in, current);
        }
        case 4:
        {
            return _iceD_getEventData(in, current);
        }
        case 5:
        {
            return _iceD_getEventsData(in, current);
        }
        case 6:
        {
            return _iceD_getTenEvents(in, current);
        }
        case 7:
        {
            return _iceD_ice_id(in, current);
        }
        case 8:
        {
            return _iceD_ice_ids(in, current);
        }
        case 9:
        {
            return _iceD_ice_isA(in, current);
        }
        case 10:
        {
            return _iceD_ice_ping(in, current);
        }
        case 11:
        {
            return _iceD_modifyClient(in, current);
        }
        case 12:
        {
            return _iceD_modifyEventDoubleField(in, current);
        }
        case 13:
        {
            return _iceD_modifyEventIntField(in, current);
        }
        case 14:
        {
            return _iceD_modifyEventStringField(in, current);
        }
        case 15:
        {
            return _iceD_modifyServiceDoubleField(in, current);
        }
        case 16:
        {
            return _iceD_modifyServiceIntField(in, current);
        }
        case 17:
        {
            return _iceD_modifyServiceStringField(in, current);
        }
        case 18:
        {
            return _iceD_registerClient(in, current);
        }
        case 19:
        {
            return _iceD_registerEvent(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_getEventsData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::EventDataModule::SeqEventDataPack>>& outAsync, const ::std::string& iceP_userToken, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_getEventsData_name);
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_getEventsData_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_getClientsByName(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::EventDataModule::SeqClients>>& outAsync, const ::std::string& iceP_userToken, const ::std::string& iceP_partialName, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_getClientsByName_name);
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_getClientsByName_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_partialName);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_getClientsByPhone(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::EventDataModule::SeqClients>>& outAsync, const ::std::string& iceP_userToken, const ::std::string& iceP_partialPhone, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_getClientsByPhone_name);
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_getClientsByPhone_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_partialPhone);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_getEventData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::EventDataModule::EventDataPack>>& outAsync, const ::std::string& iceP_userToken, int iceP_eventId, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_getEventData_name);
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_getEventData_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_eventId);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_getTenEvents(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::EventDataModule::SeqEventDataPack>>& outAsync, const ::std::string& iceP_userToken, const ::std::string& iceP_fromDate, int iceP_offset, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_getTenEvents_name);
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_getTenEvents_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_fromDate, iceP_offset);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_registerEvent(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::EventDataModule::EventDataPack>>& outAsync, const ::std::string& iceP_userToken, const EventDataPack& iceP_eventDataPack, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_registerEvent_name);
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_registerEvent_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_eventDataPack);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_modifyEventIntField(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_userToken, int iceP_eventId, EventField iceP_field, int iceP_newValue, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_modifyEventIntField_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_eventId, iceP_field, iceP_newValue);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_modifyEventStringField(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_userToken, int iceP_eventId, EventField iceP_field, const ::std::string& iceP_newValue, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_modifyEventStringField_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_eventId, iceP_field, iceP_newValue);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_modifyEventDoubleField(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_userToken, int iceP_eventId, EventField iceP_field, double iceP_newValue, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_modifyEventDoubleField_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_eventId, iceP_field, iceP_newValue);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_addServiceToEvent(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_userToken, const ServiceData& iceP_serviceData, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_addServiceToEvent_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_serviceData);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_modifyServiceIntField(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_userToken, int iceP_serviceId, ServiceField iceP_field, int iceP_newValue, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_modifyServiceIntField_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_serviceId, iceP_field, iceP_newValue);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_modifyServiceStringField(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_userToken, int iceP_serviceId, ServiceField iceP_field, const ::std::string& iceP_newValue, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_modifyServiceStringField_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_serviceId, iceP_field, iceP_newValue);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_modifyServiceDoubleField(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_userToken, int iceP_serviceId, ServiceField iceP_field, double iceP_newValue, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_modifyServiceDoubleField_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_serviceId, iceP_field, iceP_newValue);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_registerClient(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>& outAsync, const ::std::string& iceP_userToken, const ClientData& iceP_clientData, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_registerClient_name);
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_registerClient_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_clientData);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_modifyClient(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_userToken, const ClientData& iceP_clientData, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_modifyClient_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_clientData);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::EventsDataInterfacePrx::_iceI_deleteRecord(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_userToken, Table iceP_table, int iceP_id, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_EventDataModule_EventsDataInterface_deleteRecord_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_userToken, iceP_table, iceP_id);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
EventDataModule::EventsDataInterfacePrx::_newInstance() const
{
    return ::IceInternal::createProxy<EventsDataInterfacePrx>();
}
/// \endcond

const ::std::string&
EventDataModule::EventsDataInterfacePrx::ice_staticId()
{
    return EventsDataInterface::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_EventDataModule_EventsDataInterface_getEventsData_name = "getEventsData";

const ::std::string iceC_EventDataModule_EventsDataInterface_getClientsByName_name = "getClientsByName";

const ::std::string iceC_EventDataModule_EventsDataInterface_getClientsByPhone_name = "getClientsByPhone";

const ::std::string iceC_EventDataModule_EventsDataInterface_getEventData_name = "getEventData";

const ::std::string iceC_EventDataModule_EventsDataInterface_getTenEvents_name = "getTenEvents";

const ::std::string iceC_EventDataModule_EventsDataInterface_registerEvent_name = "registerEvent";

const ::std::string iceC_EventDataModule_EventsDataInterface_modifyEventIntField_name = "modifyEventIntField";

const ::std::string iceC_EventDataModule_EventsDataInterface_modifyEventStringField_name = "modifyEventStringField";

const ::std::string iceC_EventDataModule_EventsDataInterface_modifyEventDoubleField_name = "modifyEventDoubleField";

const ::std::string iceC_EventDataModule_EventsDataInterface_addServiceToEvent_name = "addServiceToEvent";

const ::std::string iceC_EventDataModule_EventsDataInterface_modifyServiceIntField_name = "modifyServiceIntField";

const ::std::string iceC_EventDataModule_EventsDataInterface_modifyServiceStringField_name = "modifyServiceStringField";

const ::std::string iceC_EventDataModule_EventsDataInterface_modifyServiceDoubleField_name = "modifyServiceDoubleField";

const ::std::string iceC_EventDataModule_EventsDataInterface_registerClient_name = "registerClient";

const ::std::string iceC_EventDataModule_EventsDataInterface_modifyClient_name = "modifyClient";

const ::std::string iceC_EventDataModule_EventsDataInterface_deleteRecord_name = "deleteRecord";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::EventDataModule::upCast(EventsDataInterface* p) { return p; }

void
::IceProxy::EventDataModule::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< EventsDataInterface>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new EventsDataInterface;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_getEventsData(const ::std::string& iceP_userToken, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_getEventsData_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_getEventsData_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_getEventsData_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_getEventsData_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::EventDataModule::SeqEventDataPack
IceProxy::EventDataModule::EventsDataInterface::end_getEventsData(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_EventDataModule_EventsDataInterface_getEventsData_name);
    ::EventDataModule::SeqEventDataPack ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_getClientsByName(const ::std::string& iceP_userToken, const ::std::string& iceP_partialName, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_getClientsByName_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_getClientsByName_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_getClientsByName_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_partialName);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_getClientsByName_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::EventDataModule::SeqClients
IceProxy::EventDataModule::EventsDataInterface::end_getClientsByName(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_EventDataModule_EventsDataInterface_getClientsByName_name);
    ::EventDataModule::SeqClients ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_getClientsByPhone(const ::std::string& iceP_userToken, const ::std::string& iceP_partialPhone, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_getClientsByPhone_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_getClientsByPhone_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_getClientsByPhone_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_partialPhone);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_getClientsByPhone_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::EventDataModule::SeqClients
IceProxy::EventDataModule::EventsDataInterface::end_getClientsByPhone(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_EventDataModule_EventsDataInterface_getClientsByPhone_name);
    ::EventDataModule::SeqClients ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_getEventData(const ::std::string& iceP_userToken, ::Ice::Int iceP_eventId, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_getEventData_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_getEventData_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_getEventData_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_eventId);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_getEventData_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::EventDataModule::EventDataPack
IceProxy::EventDataModule::EventsDataInterface::end_getEventData(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_EventDataModule_EventsDataInterface_getEventData_name);
    ::EventDataModule::EventDataPack ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_getTenEvents(const ::std::string& iceP_userToken, const ::std::string& iceP_fromDate, ::Ice::Int iceP_offset, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_getTenEvents_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_getTenEvents_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_getTenEvents_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_fromDate);
        ostr->write(iceP_offset);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_getTenEvents_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::EventDataModule::SeqEventDataPack
IceProxy::EventDataModule::EventsDataInterface::end_getTenEvents(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_EventDataModule_EventsDataInterface_getTenEvents_name);
    ::EventDataModule::SeqEventDataPack ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_registerEvent(const ::std::string& iceP_userToken, const ::EventDataModule::EventDataPack& iceP_eventDataPack, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_registerEvent_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_registerEvent_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_registerEvent_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_eventDataPack);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_registerEvent_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::EventDataModule::EventDataPack
IceProxy::EventDataModule::EventsDataInterface::end_registerEvent(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_EventDataModule_EventsDataInterface_registerEvent_name);
    ::EventDataModule::EventDataPack ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_modifyEventIntField(const ::std::string& iceP_userToken, ::Ice::Int iceP_eventId, ::EventDataModule::EventField iceP_field, ::Ice::Int iceP_newValue, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_modifyEventIntField_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_modifyEventIntField_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_eventId);
        ostr->write(iceP_field);
        ostr->write(iceP_newValue);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_modifyEventIntField_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::EventDataModule::EventsDataInterface::end_modifyEventIntField(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_EventDataModule_EventsDataInterface_modifyEventIntField_name);
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_modifyEventStringField(const ::std::string& iceP_userToken, ::Ice::Int iceP_eventId, ::EventDataModule::EventField iceP_field, const ::std::string& iceP_newValue, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_modifyEventStringField_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_modifyEventStringField_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_eventId);
        ostr->write(iceP_field);
        ostr->write(iceP_newValue);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_modifyEventStringField_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::EventDataModule::EventsDataInterface::end_modifyEventStringField(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_EventDataModule_EventsDataInterface_modifyEventStringField_name);
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_modifyEventDoubleField(const ::std::string& iceP_userToken, ::Ice::Int iceP_eventId, ::EventDataModule::EventField iceP_field, ::Ice::Double iceP_newValue, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_modifyEventDoubleField_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_modifyEventDoubleField_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_eventId);
        ostr->write(iceP_field);
        ostr->write(iceP_newValue);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_modifyEventDoubleField_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::EventDataModule::EventsDataInterface::end_modifyEventDoubleField(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_EventDataModule_EventsDataInterface_modifyEventDoubleField_name);
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_addServiceToEvent(const ::std::string& iceP_userToken, const ::EventDataModule::ServiceData& iceP_serviceData, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_addServiceToEvent_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_addServiceToEvent_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_serviceData);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_addServiceToEvent_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::EventDataModule::EventsDataInterface::end_addServiceToEvent(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_EventDataModule_EventsDataInterface_addServiceToEvent_name);
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_modifyServiceIntField(const ::std::string& iceP_userToken, ::Ice::Int iceP_serviceId, ::EventDataModule::ServiceField iceP_field, ::Ice::Int iceP_newValue, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_modifyServiceIntField_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_modifyServiceIntField_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_serviceId);
        ostr->write(iceP_field);
        ostr->write(iceP_newValue);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_modifyServiceIntField_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::EventDataModule::EventsDataInterface::end_modifyServiceIntField(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_EventDataModule_EventsDataInterface_modifyServiceIntField_name);
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_modifyServiceStringField(const ::std::string& iceP_userToken, ::Ice::Int iceP_serviceId, ::EventDataModule::ServiceField iceP_field, const ::std::string& iceP_newValue, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_modifyServiceStringField_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_modifyServiceStringField_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_serviceId);
        ostr->write(iceP_field);
        ostr->write(iceP_newValue);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_modifyServiceStringField_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::EventDataModule::EventsDataInterface::end_modifyServiceStringField(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_EventDataModule_EventsDataInterface_modifyServiceStringField_name);
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_modifyServiceDoubleField(const ::std::string& iceP_userToken, ::Ice::Int iceP_serviceId, ::EventDataModule::ServiceField iceP_field, ::Ice::Double iceP_newValue, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_modifyServiceDoubleField_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_modifyServiceDoubleField_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_serviceId);
        ostr->write(iceP_field);
        ostr->write(iceP_newValue);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_modifyServiceDoubleField_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::EventDataModule::EventsDataInterface::end_modifyServiceDoubleField(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_EventDataModule_EventsDataInterface_modifyServiceDoubleField_name);
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_registerClient(const ::std::string& iceP_userToken, const ::EventDataModule::ClientData& iceP_clientData, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_EventDataModule_EventsDataInterface_registerClient_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_registerClient_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_registerClient_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_clientData);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_registerClient_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Ice::Int
IceProxy::EventDataModule::EventsDataInterface::end_registerClient(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_EventDataModule_EventsDataInterface_registerClient_name);
    ::Ice::Int ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_modifyClient(const ::std::string& iceP_userToken, const ::EventDataModule::ClientData& iceP_clientData, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_modifyClient_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_modifyClient_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_clientData);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_modifyClient_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::EventDataModule::EventsDataInterface::end_modifyClient(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_EventDataModule_EventsDataInterface_modifyClient_name);
}

::Ice::AsyncResultPtr
IceProxy::EventDataModule::EventsDataInterface::_iceI_begin_deleteRecord(const ::std::string& iceP_userToken, ::EventDataModule::Table iceP_table, ::Ice::Int iceP_id, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_EventDataModule_EventsDataInterface_deleteRecord_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_EventDataModule_EventsDataInterface_deleteRecord_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_userToken);
        ostr->write(iceP_table);
        ostr->write(iceP_id);
        result->endWriteParams();
        result->invoke(iceC_EventDataModule_EventsDataInterface_deleteRecord_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::EventDataModule::EventsDataInterface::end_deleteRecord(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_EventDataModule_EventsDataInterface_deleteRecord_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::EventDataModule::EventsDataInterface::_newInstance() const
{
    return new EventsDataInterface;
}
/// \endcond

const ::std::string&
IceProxy::EventDataModule::EventsDataInterface::ice_staticId()
{
    return ::EventDataModule::EventsDataInterface::ice_staticId();
}

EventDataModule::EventsDataInterface::~EventsDataInterface()
{
}

/// \cond INTERNAL
::Ice::Object* EventDataModule::upCast(EventsDataInterface* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_EventDataModule_EventsDataInterface_ids[2] =
{
    "::EventDataModule::EventsDataInterface",
    "::Ice::Object"
};

}

bool
EventDataModule::EventsDataInterface::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_EventDataModule_EventsDataInterface_ids, iceC_EventDataModule_EventsDataInterface_ids + 2, s);
}

::std::vector< ::std::string>
EventDataModule::EventsDataInterface::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_EventDataModule_EventsDataInterface_ids[0], &iceC_EventDataModule_EventsDataInterface_ids[2]);
}

const ::std::string&
EventDataModule::EventsDataInterface::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
EventDataModule::EventsDataInterface::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::EventDataModule::EventsDataInterface";
    return typeId;
#else
    return iceC_EventDataModule_EventsDataInterface_ids[0];
#endif
}

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_getEventsData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    istr->read(iceP_userToken);
    inS.endReadParams();
    SeqEventDataPack ret = this->getEventsData(iceP_userToken, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_getClientsByName(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ::std::string iceP_partialName;
    istr->read(iceP_userToken);
    istr->read(iceP_partialName);
    inS.endReadParams();
    SeqClients ret = this->getClientsByName(iceP_userToken, iceP_partialName, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_getClientsByPhone(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ::std::string iceP_partialPhone;
    istr->read(iceP_userToken);
    istr->read(iceP_partialPhone);
    inS.endReadParams();
    SeqClients ret = this->getClientsByPhone(iceP_userToken, iceP_partialPhone, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_getEventData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ::Ice::Int iceP_eventId;
    istr->read(iceP_userToken);
    istr->read(iceP_eventId);
    inS.endReadParams();
    EventDataPack ret = this->getEventData(iceP_userToken, iceP_eventId, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_getTenEvents(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ::std::string iceP_fromDate;
    ::Ice::Int iceP_offset;
    istr->read(iceP_userToken);
    istr->read(iceP_fromDate);
    istr->read(iceP_offset);
    inS.endReadParams();
    SeqEventDataPack ret = this->getTenEvents(iceP_userToken, iceP_fromDate, iceP_offset, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_registerEvent(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    EventDataPack iceP_eventDataPack;
    istr->read(iceP_userToken);
    istr->read(iceP_eventDataPack);
    inS.endReadParams();
    EventDataPack ret = this->registerEvent(iceP_userToken, iceP_eventDataPack, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyEventIntField(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ::Ice::Int iceP_eventId;
    EventField iceP_field;
    ::Ice::Int iceP_newValue;
    istr->read(iceP_userToken);
    istr->read(iceP_eventId);
    istr->read(iceP_field);
    istr->read(iceP_newValue);
    inS.endReadParams();
    this->modifyEventIntField(iceP_userToken, iceP_eventId, iceP_field, iceP_newValue, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyEventStringField(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ::Ice::Int iceP_eventId;
    EventField iceP_field;
    ::std::string iceP_newValue;
    istr->read(iceP_userToken);
    istr->read(iceP_eventId);
    istr->read(iceP_field);
    istr->read(iceP_newValue);
    inS.endReadParams();
    this->modifyEventStringField(iceP_userToken, iceP_eventId, iceP_field, iceP_newValue, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyEventDoubleField(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ::Ice::Int iceP_eventId;
    EventField iceP_field;
    ::Ice::Double iceP_newValue;
    istr->read(iceP_userToken);
    istr->read(iceP_eventId);
    istr->read(iceP_field);
    istr->read(iceP_newValue);
    inS.endReadParams();
    this->modifyEventDoubleField(iceP_userToken, iceP_eventId, iceP_field, iceP_newValue, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_addServiceToEvent(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ServiceData iceP_serviceData;
    istr->read(iceP_userToken);
    istr->read(iceP_serviceData);
    inS.endReadParams();
    this->addServiceToEvent(iceP_userToken, iceP_serviceData, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyServiceIntField(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ::Ice::Int iceP_serviceId;
    ServiceField iceP_field;
    ::Ice::Int iceP_newValue;
    istr->read(iceP_userToken);
    istr->read(iceP_serviceId);
    istr->read(iceP_field);
    istr->read(iceP_newValue);
    inS.endReadParams();
    this->modifyServiceIntField(iceP_userToken, iceP_serviceId, iceP_field, iceP_newValue, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyServiceStringField(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ::Ice::Int iceP_serviceId;
    ServiceField iceP_field;
    ::std::string iceP_newValue;
    istr->read(iceP_userToken);
    istr->read(iceP_serviceId);
    istr->read(iceP_field);
    istr->read(iceP_newValue);
    inS.endReadParams();
    this->modifyServiceStringField(iceP_userToken, iceP_serviceId, iceP_field, iceP_newValue, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyServiceDoubleField(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ::Ice::Int iceP_serviceId;
    ServiceField iceP_field;
    ::Ice::Double iceP_newValue;
    istr->read(iceP_userToken);
    istr->read(iceP_serviceId);
    istr->read(iceP_field);
    istr->read(iceP_newValue);
    inS.endReadParams();
    this->modifyServiceDoubleField(iceP_userToken, iceP_serviceId, iceP_field, iceP_newValue, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_registerClient(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ClientData iceP_clientData;
    istr->read(iceP_userToken);
    istr->read(iceP_clientData);
    inS.endReadParams();
    ::Ice::Int ret = this->registerClient(iceP_userToken, iceP_clientData, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_modifyClient(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    ClientData iceP_clientData;
    istr->read(iceP_userToken);
    istr->read(iceP_clientData);
    inS.endReadParams();
    this->modifyClient(iceP_userToken, iceP_clientData, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceD_deleteRecord(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_userToken;
    Table iceP_table;
    ::Ice::Int iceP_id;
    istr->read(iceP_userToken);
    istr->read(iceP_table);
    istr->read(iceP_id);
    inS.endReadParams();
    this->deleteRecord(iceP_userToken, iceP_table, iceP_id, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_EventDataModule_EventsDataInterface_all[] =
{
    "addServiceToEvent",
    "deleteRecord",
    "getClientsByName",
    "getClientsByPhone",
    "getEventData",
    "getEventsData",
    "getTenEvents",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "modifyClient",
    "modifyEventDoubleField",
    "modifyEventIntField",
    "modifyEventStringField",
    "modifyServiceDoubleField",
    "modifyServiceIntField",
    "modifyServiceStringField",
    "registerClient",
    "registerEvent"
};

}

/// \cond INTERNAL
bool
EventDataModule::EventsDataInterface::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_EventDataModule_EventsDataInterface_all, iceC_EventDataModule_EventsDataInterface_all + 20, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_EventDataModule_EventsDataInterface_all)
    {
        case 0:
        {
            return _iceD_addServiceToEvent(in, current);
        }
        case 1:
        {
            return _iceD_deleteRecord(in, current);
        }
        case 2:
        {
            return _iceD_getClientsByName(in, current);
        }
        case 3:
        {
            return _iceD_getClientsByPhone(in, current);
        }
        case 4:
        {
            return _iceD_getEventData(in, current);
        }
        case 5:
        {
            return _iceD_getEventsData(in, current);
        }
        case 6:
        {
            return _iceD_getTenEvents(in, current);
        }
        case 7:
        {
            return _iceD_ice_id(in, current);
        }
        case 8:
        {
            return _iceD_ice_ids(in, current);
        }
        case 9:
        {
            return _iceD_ice_isA(in, current);
        }
        case 10:
        {
            return _iceD_ice_ping(in, current);
        }
        case 11:
        {
            return _iceD_modifyClient(in, current);
        }
        case 12:
        {
            return _iceD_modifyEventDoubleField(in, current);
        }
        case 13:
        {
            return _iceD_modifyEventIntField(in, current);
        }
        case 14:
        {
            return _iceD_modifyEventStringField(in, current);
        }
        case 15:
        {
            return _iceD_modifyServiceDoubleField(in, current);
        }
        case 16:
        {
            return _iceD_modifyServiceIntField(in, current);
        }
        case 17:
        {
            return _iceD_modifyServiceStringField(in, current);
        }
        case 18:
        {
            return _iceD_registerClient(in, current);
        }
        case 19:
        {
            return _iceD_registerEvent(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
EventDataModule::EventsDataInterface::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< EventsDataInterface, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
EventDataModule::EventsDataInterface::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< EventsDataInterface, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
EventDataModule::_icePatchObjectPtr(EventsDataInterfacePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = EventsDataInterfacePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(EventsDataInterface::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
